import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { scanAppComponents } from './inventory';

const inventory = scanAppComponents(process.cwd());
const output = resolve('src/shared/ui/gallery/componentInventory.generated.ts');
writeFileSync(output, `// Generated by tools/ui-gallery/generate.ts; run node --import tsx tools/ui-gallery/generate.ts.\n// Metadata only: do not import app components here.\nexport const appComponentInventory = [\n${inventory.map(component => `  ${JSON.stringify(component)}`).join(',\n')}\n];\n`);
console.log(`Generated ${inventory.length} app component entries.`);
